version: "3.9"

services:
  server:
    container_name: server-container
    build:
      context: .
      dockerfile: build/server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network

  client:
    container_name: client-container
    build:
      context: .
      dockerfile: build/client/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ServerAddressDocker=server-container:8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
